import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Hero from "./trackShipment/Hero";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ }) {
  return (
    <html lang="en">
      <body>
        <Hero />  
      </body>
    </html>
  );
}
